name: ble_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  provider: ^6.0.5
  flutter_blue_plus: ^1.14.1
  mobile_scanner: ^3.2.0
  flutter_svg: ^2.0.17
  qr_flutter: ^4.1.0
  slider_button: ^2.0.0
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  binary: ^3.0.1
  permission_handler: ^11.3.0
  location: ^5.0.0
  flutter_dotenv: ^5.0.2
  number_system: 0.0.6+8
  mockito: 5.4.4

  # HERE SDK (local path)
  here_sdk:
    path: plugins/here_sdk

dependency_overrides:
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-VariableFont_opsz,wght.ttf
        - asset: fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf
