name: ble_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  flutter_dotenv: ^5.0.2  # For managing API keys securely
  location: ^5.0.0  # For handling device location
  permission_handler: ^11.3.0 
  intl: ^0.19.0
  flutter_blue_plus: 1.34.5
  slider_button: ^2.0.0
  provider: 6.0.2
  percent_indicator: 4.0.1
  mobile_scanner: 3.1.1
  mockito: 5.4.4
  number_system: 0.0.6+8
  binary: 3.0.1
  flutter_svg: ^2.0.17
  qr_flutter: ^4.0.0
  
dependency_overrides:
  vibration: ^3.1.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-VariableFont_opsz,wght.ttf
        - asset: fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf
          